config.go
This is in service of additional PRs ([here](https://github.com/speakeasy-api/openapi-generation/pull/147)) in order to power "data driven" frontend
=> [SPE-1150] Add language config field type

config.go
Simple backward compatible change to add config for dev containers.
I could also but this under language config or generation, open to whatever we think is best here.
Fixes SPE-1983
=> feat: config for dev containers

workflow/common.go, workflow/source_test.go
We were not handling paths correctly that are formatted like the following
`~/speakeasy/openapi.yaml`
`/Users/ryanalbert/speakeasy/openapi.yaml`
This is because ~ breaks os.Stat even if you are using filepath.Abs. You need to actually replace the ~ with the UserHomeDir.
The ordering of the getFileStatus function was also problematic. A path like `/Users/ryanalbert/speakeasy/openapi.yaml` does not error on ParseRequestURI so we were recognizing it as a remote URL.
=> fix: file status function

workflow/source.go, workflow/source_test.go
This PR adds to sources a publish field for pushing to the registry.
It also removes a validation that is unnecessary (I think?) and gets in the way of some of the changes we want to make for the Bundler
For example, it's perfectly valid to have one input spec and set the output to `speakeasy://my-image`
Also, I don't see a reason why someone can't have one input spec and an output like `./output/openapi.yaml`. If they want to move it, then 🤷
=> chore: update source model for registry

workflow/workflow.go
This is risk-free, but needed for testing. We can always remove it later if we don't go through with the feature
=> feat: add speakeasyVersion field

workflow/common.go, workflow/source.go
Sets up some utility functions we will need when loading registry documents. These could be used by speakeasy-core, speakeasy-registry, or speakeasy (CLI)
- Determines whether an input document is a registry reference
- Parses a registry reference URL into relevant OCI components we will need when loading the document orgSlug, workspaceSlug, namespaceName, reference
=> feat: utilities for loading registry documents

configuration.go, io_test.go
We decided to instead make this a target-level config flag.
=> fix: remove unused methodSignaturesApr2024 flag

configuration.go
Reference: https://linear.app/speakeasy/issue/SPE-4016/feature-add-mockserver-generation-configuration-flag
Reference: https://linear.app/speakeasy/issue/SPE-4011/feature-enable-mockserver-generation-for-customers
Introduces a new `mockServer` configuration object under the `generation` object that will be used to configure generation settings for the mock server that will be eventually bundled with test generation. While the mock server is under development, the generator will explicitly look for the `MockServer` configuration object to be present and `disabled` to be `false`. When we want to enable mock server generation for customers, we will update that logic to treat missing `MockServer` as "enabled" or if the object is present, respect the `disabled` flag (effectively making it …
=> feat: Add gen.yaml generation.mockServer configuration

io_test.go, testdata/v200-generation-mockserver-disabled.yaml
Reference: https://linear.app/speakeasy/issue/SPE-4016/feature-add-mockserver-generation-configuration-flag
=> chore: Add mockServer.disabled load test

workflow/lockfile.go
=> chore: remove outputLocation from workflow.lock

workflow/source.go, workflow/source_test.go
fixes SPE-4094 (support interpolated spec paths on Workflows) though has changes throughout several other repositories.
Changed the type of `Location` such that we're forced to make a decision on if we want variable expansion in each place, because in multiple prompts using charm/bubbletea we actually want to reference the env variable as "$something", whereas we need to resolve it when we're actually working with a resolved value.
=> chore: support env variables in workflow locations

schemas/workflow.schema.json, workflow/target.go
Add settings to allow more configuration options for label and lang in codeSamples
=> feat: add codesamples override options to workflow config

configuration.go, workflow/source.go
The end effect of this is that `run` will output `json` files when applying overlays to input json specs
=> chore: respect input file extension type when getting source output path

configuration.go, lockfile.go
Tracking time of generation in gen.lock may be useful for GH actions usecases
=> feat: tracking generation time and workflow dispatch in publishing

workflow/workflow.go, workflow/workflow_test.go
Didn't account for people who already had codeSamples but weren't being pushed to the regsitry
=> fix: codeSamples migrate NPE

schemas/workflow.schema.json, workflow/target.go, workflow/target_test.go, workflow/workflow_test.go
Reference: https://linear.app/speakeasy/issue/GEN-590/feature-workflow-configuration-updates-for-target-testing
This change enables the following opt-in workflow configuration so customers can enable target testing via `speakeasy run` and direct/test mode in GitHub Actions:
```yaml
sources:
SOURCE_NAME:
inputs:
- # ...
targets:
TARGET_NAME:
source: SOURCE_NAME
target: TARGET
testing:
enabled: true
```
=> feat: Initial workflow target testing configuration

workflow/workflow.go, workflow/workflow_test.go
Probably the last time we can easily make a change like this, as soon the codeSamples namespaces will be depended on
=> fix: add target type to codeSamples namespaces

workflow/source.go, workflow/source_test.go
I missed the actual Validation logic for the transforms in the first PR
This pull request to `workflow/source.go` includes changes to enhance the validation logic for transformations and streamline the codebase. The most important changes include the addition of a new list of transformation types and modifications to the validation method to use this list.
Enhancements to validation logic:
* Added a `transformList` variable containing the transformation types: "removeUnused", "filterOperations", "cleanup", "format", and "normalize".
* Modified the `Validate` method in the `Transformation` struct to include checks for `Format` and `Normalize` fields and updated the error message to use the new `transformList` variable.
=> fix: corrected the tranform validation logic

workflow/workflow.go, workflow/workflow_test.go
https://linear.app/speakeasy/issue/SPE-4523/default-to-language-label-for-new-codesamples
Many people using codeSamples for docs want the samples to be labeled as SDK codeSamples such as Go (SDK). The default right now shows up as duplicated operation name which is not super useful. We are only doing this for net new workflows right now.
=> feat: default language label for codesamples

workflow/source.go, workflow/source_test.go
I am adding support for outputting `json` during merge.
This also makes it so all "source operations" (merge / overlay / transform) will write `json` if the output is meant to be json
=> feat: support json out during merge

configuration.go, io_test.go
Introduces a flag for csharp usage snippets that is referenced in [#2705](https://github.com/speakeasy-api/openapi-generation/pull/2705)
=> chore: add flags for controlling SDK init style

go.mod, go.sum, workflow/source.go, workflow/source_test.go
Supports fallback syntax, and multiple vars:
Name | Env | Value | Want
-- | -- | -- | --
simple substitution | {"SDKGEN_ROOT": "/tmp"} | ${SDKGEN_ROOT}/spec.yaml | /tmp/spec.yaml
fallback substitution | {"SDKGEN_OPTION": ""} | ${SDKGEN_OPTION:-default-value} | default-value
colon plus substitution | {"SDKGEN_FEATURE": "enabled"} | /config${SDKGEN_FEATURE:+/premium} | /config/premium
multiple substitutions | {"SDKGEN_HOST": "api.example.com", "SDKGEN_VERSION": "v1"} | https://${SDKGEN_HOST}/${SDKGEN_VERSION} | https://api.example.com/v1
</div></div><br class="Apple-interchange-newline">
=> feat: union syntax on env vars
